### ISSUE TITLE
Shifted Chromosome and Contig Boundaries [BUG]

### ISSUE THREAD

**Issue by mcbbaker** [theaidenlab/juicebox#1014]
**Describe the bug**
A portion of the heatmap is outside of the chromosome boundary. It also appears that the boundaries of the contigs are shifted upwards and need to be shifted downwards to properly fit the HiC data (see screenshots). This incorrect overlay makes it difficult to fix misassemblies properly. 

**To Reproduce**
1. Zoom in to the end of the chromosome and observe heatmap and chromosome boundaries.
2. Zoom in to heatmap and view overlay of contig boundaries on heatmap. 

**Expected behavior**
The heatmap should be fully contained within the boundaries of the chromosome. The overlay of the contig boundaries on the HiC data should not appear shifted.

**Screenshots**
![image](https://github.com/aidenlab/Juicebox/assets/118228251/c8d83f1a-4fa5-49a5-a1a2-c51aa2e7bb6b)
![image](https://github.com/aidenlab/Juicebox/assets/118228251/73d1b597-9f2e-49a7-8653-d52cd99e4a79)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Juicebox Version 1.9.8

**Additional context**
This issue has appeared for a few different assemblies I've corrected (same version and desktop).

**Comment by mcbbaker** [comment]
I am closing this as I figured out what was going on here. The 100bp gaps that contribute to the .size file as input to pre are not accounted for in the assembly file and the difference accumulates with bigger genomes.

**Comment by Isoris** [comment]
So you need to split at gaps and rejoin? how did you do it?
