### ISSUE TITLE
False error "Cannot load maps with different genomes"

### ISSUE THREAD

**Issue by ArielPaulson** [theaidenlab/juicebox#970]
Latest Mac Juicebox (1.11.08, on Catalina 10.15.7, latest Java) cannot load certain merged HiC files on the same genome, it thinks they are on different genomes.   However, the web Juicebox can load them just fine.  There are other users here having the same issue.

I have two strains, S and P, aligned to the same genome.  Each has three replicates.  The un-merged replicate pairs load just fine, i.e. P1 + S1, P2 + S2, P3 + S3.  

But when I merge S1-3 into merged-S, and P1-3 into merged-P, the two merged hic files will not load into desktop Juicebox.

I'd like to think it is a version thing, but the two earlier versions of desktop Juicebox fail to load the files at all, they don't even try to load.  After selecting the files, the interface just sits there like nothing happened.

The files are not corrupted in any obvious way, I have dumped all the chr-pair matrices at multiple resolutions and imported the data into other softwares.  Also I have run multiple hiccups and POSSUMM runs on the merged .hic files with no issues.

Thanks,
Ariel

**Comment by sa501428** [comment]
@ArielPaulson do you still get the bug with the latest dev versions?https://github.com/aidenlab/Juicebox/releases/tag/v2.13.05 (using the Juicebox jar)

**Comment by ArielPaulson** [comment]
It is still happening with the 2.13.05 jar.

I don't know if it helps, but the command line messages during this process were:

$ java -version
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)

$ java -Xms512m -Xmx2048m -jar juicebox.2.13.05.jar
Fetching user directory... Default User Directory: /Users/apa
WARN [2021-11-11T11:15:12,567]  [Globals.java:138] [main]  Development mode is enabled
HiC Directory: /Users/apa/juicebox
Window W: 1920 H1397
INFO [2021-11-11T11:15:28,754]  [DirectoryManager.java:179] [main]  IGV Directory: /Users/apa/igv
Listening on port 30000
HiC file version: 8
HiC file version: 8
Unable to get desired file name
1
Exiting Main Window

**Comment by sa501428** [comment]
@ArielPaulson it should be resolved: https://github.com/aidenlab/Juicebox/releases/tag/v.2.13.07
Let us know if there's still an issue. 
It should also now print out the mismatch in the terminal.
