### ISSUE TITLE
[BUG] Error loading hic file with files generated from salsa using juicer_tools pre

### ISSUE THREAD

**Issue by oneillkza** [theaidenlab/juicebox#973]
**Describe the bug**

**To Reproduce**
1. File > Open > Local > select file
2. Popup appears. "Error loading .hic file"

Console output:
```
HiC file version: 9
Error reading datasetnull
Error loading hic file null
```

**Expected behavior**
JuiceBox opens the hic file.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: confirmed to occur with both 1.9.8 and 1.11.08. Does not occur with the web version of Juicebox.

**Additional context**
I made a .hic file using the `convert.sh` from SALSA. This uses juicer_tools pre (version `juicer_tools_2.13.06.jar`). The hic file opens fine in the web version of juicebox, but throws an error with the downloadable .jar

**Comment by sa501428** [comment]
If you're using a 2.x dev jar, you'll need to use the latest 2.x juicebox.jar from the releases. See https://github.com/aidenlab/Juicebox/issues/966

**Comment by oneillkza** [comment]
Thanks @sa501428 !

Just as an FYI, your readme.md is still telling people to download Juicebox from the links on [this wiki page that hasn't been updated since 2019](https://github.com/aidenlab/Juicebox/wiki/Download), and which says that 1.11.08 is the latest beta version (!)

**Comment by sa501428** [comment]
I've updated the wiki. Thanks for catching that!
