### ISSUE TITLE
The format of mndindex file?

### ISSUE THREAD

**Issue by xiekunwhy** [theaidenlab/juicebox#974]
Hi,

There is an option to accept mndindex file in juicer_tools, but there is no information to describe the format of mndindex, would you please add some?

Best,
Kun

**Comment by xiekunwhy** [comment]
java -Xmx50G -jar juicer_tools.jar pre -n -j 10 --threads 10 scaffold.revision.aln.txt scaffold.revision.hic scaffold.revision.fa.size
No mndIndex provided
Using single threaded preprocessor

Any one knows?

**Comment by sa501428** [comment]
This optional flag is in development for Juicer 2 / we'll aim to get details out asap. You can try using Juicer 2 here: https://github.com/aidenlab/juicer

**Comment by xiekunwhy** [comment]
I still don't know how to prepare mndIndex file.
