### ISSUE TITLE
[BUG] Error loading .hic file

### ISSUE THREAD

**Issue by Delta-43** [theaidenlab/juicebox#979]
Hello,
   I'm trying to load .hic data from the Juicebox archives on the desktop version, but for some reason it cannot access the .hic hosted online.
I'm running Juicebox version 1.11.08 .jar file on Ubuntu 20.04 LTS and have faced this issue on 2 separate systems on 2 different networks. Oddly, the same jar file works fine on a Windows system and the .hic file can also be loaded on the Juicebox web server.
   I would be grateful for any help !

**Comment by ArielPaulson** [comment]
I have what I think might be the same issue, I have Juicebox 1.11.08 running on Mac Catalina 10.15.7 and some days I can load my hic files (over http) and other days I just get the extremely generic error "error loading .hic file".  I can load these files in the web version just fine.  Again the weird things is that some days they load and other days, they won't.

**Comment by sa501428** [comment]
We've typically seen this when there are VPN or firewall issues.

**Comment by Delta-43** [comment]
My firewall is disabled and there's no VPN enabled. I have tried to load the Bonev et. al dataset on 3 computer (Windows, Ubuntu, MacOS) via 3 different networks (Institute Network, Eduroam and Mobile Tethered) respectively. The Juciebox jar regularly fails to load the files in a linux environment but works fine on the Windows and MacOS platforms.

The output on the console doesn't show any specific error that I can understand:
```
Fetching user directory... Default User Directory: /home/bioinfo
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
WARN [2022-03-14T11:13:02,083]  [Globals.java:138] [main]  Development mode is enabled
HiC Directory: /home/bioinfo/juicebox
Window W: 1440 H1080
Listening on port 30000
Error loading hic file http://hicfiles.s3.amazonaws.com/external/bonev/ES_mapq30_30.hic
Error loading hic file http://hicfiles.s3.amazonaws.com/external/bonev/ES_mapq30_30.hic
Exiting Main Window
```
Any help would be much appreciated, thanks.

**Comment by ArielPaulson** [comment]
Likewise, I don't have a firewall issue since I am loading files from my local network, albeit over http.  I can still open the file as a "local" file, but browsing to it on a mac takes a long time, but with http I can just drop in the url and it is vastly faster.  Except http is very random in when it works or doesn't work.

My console output is:

Fetching user directory... Default User Directory: /Users/apa
WARN [2022-03-14T10:19:46,199]  [Globals.java:138] [main]  Development mode is enabled
HiC Directory: /Users/apa/juicebox
Window W: 1920 H1397
Listening on port 30000
Error loading hic file sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by tonyjhlam** [comment]
I am having the same issue, but trying to load a local hic file

**Comment by sa501428** [comment]
I'm not sure that these are the same issues. 
@Delta-43, this file doesn't exist: 
http://hicfiles.s3.amazonaws.com/external/bonev/ES_mapq30_30.hic
But this one does:
https://hicfiles.s3.amazonaws.com/external/bonev/ES_mapq30.hic
This appears to be a bug in either the S3 bucket or the menu. @weiszd were there any recent changes to the S3 hosting?

@ArielPaulson is it possible that the local web server you're running has a log when the files fail to load? Maybe it stops running at times? Can you create a new/separate issue for this?

@tonyjhlam is your issue similar to @ArielPaulson 's or @Delta-43 's? Or something different?

**Comment by tonyjhlam** [comment]
@sa501428 I think my issue is similar to @ArielPaulson 

I am using SLURM Juicer v2.0, trying to open a .hic file locally.
I cannot view .hic files on Desktop version of Juicebox, but having no issue viewing when using the online web version. I've given my .hic file to a colleague, and he is unable to open the .hic file with his desktop version of juicebox. However, he is able to open his 'old' .hic files that was made with Juicer v1.XX? 

Could this possibly be an issue with SLURM or JUICER v2.0? 

I will create a separate issue. #980

**Comment by sa501428** [comment]
I think @tonyjhlam 's question was a version issue / hopefully resolved on that other thread.

**Comment by Delta-43** [comment]
> 

Loading from the menu still fails but loading from the URL you mentioned works. Maybe the links are corrupted in some file.
Also trying to download the files results in a Forbidden 403 error.

**Comment by Delta-43** [comment]
Update: I was trying with the links from the Recently opened sections. I tried the links from the archives directly and they are working fine now. Sorry for the confusion. I'll close the issue as resolved.

But I would still like some guidance in downloading the .hic files to local storage. The AWS links are forbidden and the Dropbox links for the Bonev et al data is empty.

**Comment by sa501428** [comment]
The Bonev et al. data/files should be on GEO.
