### ISSUE TITLE
[BUG] Error loading .hic Juicebox Desktop

### ISSUE THREAD

**Issue by tonyjhlam** [theaidenlab/juicebox#980]
Juicer: v2.0 SLURM 
Juicebox: v1.11.08

HiC files created by Juicer SLURM v2.0 is unable to load via Juicebox Desktop v1.11.08. I am able to load this file using Juicebox web. My colleague is unable to load this .hic file on his Desktop version, but confirmed that his Juicebox Desktop works with older .hic files.

**Comment by sa501428** [comment]
If you are using Juicer 2, it builds .hic files using the latest v9 format. As such, you have to use the latest Juicebox version, which we currently only have jars for (no dmg/exe executable at this time). You can find these released here: https://github.com/aidenlab/Juicebox/releases/tag/v.2.13.07
Or you can of course use the online version which is automatically up to date.

**Comment by tonyjhlam** [comment]
Thanks @sa501428, it's working with the new juicebox version.

**Comment by tonyjhlam** [comment]
@sa501428 Will I encounter any issues with downstream analysis (e.g. HiCCUPs, HiCCUPsdiff, MultiHiCCompare) with the new v9 formatting?

**Comment by sa501428** [comment]
For HiCCUPs, HiCCUPSdiff, Arrowhead, etc you'll need to use the latest Juicer Tools jar (at the same release tag). 

What's MultiHiCCompare?

**Comment by tonyjhlam** [comment]
https://academic.oup.com/bioinformatics/article/35/17/2916/5298730

It is another method for identifying differential interactions. I think it works on .hic by extracting matrices via Straw. So I guess the question would be: does Straw work with v9 formatting?

Also, what JCUDA is the new juicebox compiled with? is it still JCUDA v7?

**Comment by sa501428** [comment]
Technically straw does, but only the latest versions; I've made a github issue for MultiHiCCompare. 

Should be JCUDA 8 but I think it's compatible with 7.

**Comment by tonyjhlam** [comment]
Great, thanks for all the help. 

Is there a reason why juicebox isn't compiled with newer/newest versions of JCUDA (e.g. v10 or v11)?

**Comment by sa501428** [comment]
No particular reason, but in most cases should be backward compatible. Only HiCCUPS is affected by this.
