### ISSUE TITLE
[BUG] Error loading .hic Juicebox Desktop

### ISSUE THREAD

**Issue by kedduck** [theaidenlab/juicebox#983]
Dear developers

i got a .hic file after running 3d-dna , when i use juicebox (windows version) it report Error loading .hic file, the web serve  report "Error loading [object File]: RangeError: Offset is outside the bounds of the DataView"

when I use the realse version and old version of juicebox , it still don't work 

juicer version 1.6
juicebox version 1.11.08

Is there something wrong about my .hic file ?  

hope for your kind reply!

thanks !

**Comment by sa501428** [comment]
Hi @kedduck , can you post this to the forum: aidenlab.org/forum.html

**Comment by shuairun** [comment]
hi，i have the same question. Did you solve it?

**Comment by kedduck** [comment]
> hi，i have the same question. Did you solve it?

Hi. My problem was caused by incomplete .hic file.  I checked the log and found  the progress was broken.

Hope this is helpful.

**Comment by shuairun** [comment]
> > hi，i have the same question. Did you solve it?
> 
> Hi. My problem was caused by incomplete .hic file. I checked the log and found the progress was broken.
> 
> Hope this is helpful.

Thanks for your answer. I am checking my log, but I don't know which step was wrong. I'll try. thanks again!
