### ISSUE TITLE
juicebox.JS can be used directly online at https://aidenlab.org/juicebox[BUG]

### ISSUE THREAD

**Issue by 242652354** [theaidenlab/juicebox#984]
**Describe the bug**

> The option cannot be turned on in the online juicebox, for example “Load Map”， “Load  B Map”, "load tracks" . They didn't respond. I used the Microsoft edge browser of windows.
What is the reason？
Thanks

**Comment by sa501428** [comment]
There's not enough detail here for us to understand what bug is being encountered, if any. 
See this walkthrough for how to use Juicebox.JS:  https://aidenlab.gitbook.io/juicebox/
This is also not the correct repository to report Juicebox.JS bugs. Those should be reported here:  https://github.com/igvteam/juicebox.js
General questions should be asked here: https://groups.google.com/g/3d-genomics
