### ISSUE TITLE
Cannot load .hic file in juicebox

### ISSUE THREAD

**Issue by AnaUnix** [theaidenlab/juicebox#986]
Hi, I'm trying to load a .hic file to visualice an eukariotic genome in juicebox using windows executable (version 1.11.08). I've generated the .hic file (724 MB) using Juicer tools v1.22.01 and mapping the OmniC reads with bwa. When I tried to load the .hic file there is no error in the screen, but the map is also not loaded. Could you help me to figure out what could be going on here? Thanks!

**Comment by sa501428** [comment]
Does it load on aidenlab.org/juicebox ?

**Comment by hsiehph** [comment]
Hi, 
I also have the same issue on the same juicebox version (V1.11.08) though I am running it on a Mac OSX box.  I can load and see the map on the website (aidenlab.org/juicebox) without any problem.  Any insight would be appreciated!  Thanks!

**Comment by sa501428** [comment]
If it works online but not in the desktop app, see this thread:
https://github.com/aidenlab/Juicebox/issues/980
